### ISSUE TITLE
1.0.8 brakes compatibility with Airbrake

### ISSUE THREAD

**Issue by geoffreyd** [markevans/dragonfly#397]
Upgrading to Dragonfly 1.0.8 (from 1.0.7) causes 

```
{
  "name":"Dragonfly::TempObject::Closed",
  "message":"can't read from tempfile as TempObject has been closed",
  "stack":"/Users/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/dragonfly-1.0.8/lib/dragonfly/temp_object.rb:177:in `tempfile'\n/Users/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/dragonfly-1.0.8/lib/dragonfly/temp_object.rb:86:in `file'\n/Users/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2"
}
```

Airbrake closes the file here: https://github.com/airbrake/airbrake/blob/v4.1.0/lib/airbrake/user_informer.rb#L32

**Comment by markevans** [comment]
do you have any more backtrace? I think this actually comes from somewhere calling TempObject#file

**Comment by jeremyf** [comment]
One error I'm encountering is when Tempfile#collect is called. See airbrake/airbrake#396
